### ISSUE TITLE
Support Ubuntu 16.04

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/pr-cleanroom#10]
The current version of `pr-cleanroom` doesn't work for Ubuntu 16.04.

**TODOs**
- [ ] Make `pr-cleanroom` be able to detect the Ubuntu version
- [ ] Don't add unnecessary PPAs for Ubuntu 16.04 (e.g., `ppa:fcl-debs` and `ppa:libccd-debs`)
- [ ] Install ROS Lunar (or Kinect?) for Ubuntu 16.04
